plugins {
    id 'com.android.application'
}

android {
    namespace 'pt.horariosfamilia.r2a'
    compileSdk 37
    compileSdkMinor 0

    defaultConfig {
        applicationId 'pt.horariosfamilia.r2a.stable'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.5.0-stable'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'com.github.MuntashirAkon:libadb-android:3.1.1'
    implementation 'com.github.MuntashirAkon:sun-security-android:1.1'
    implementation 'org.conscrypt:conscrypt-android:2.5.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
}
